### ISSUE TITLE
Question about the preprocessing of dataset

### ISSUE THREAD

**Issue by xiaxin1998** [wangjlgz/HyperRec#1]
What the meaning of the interaction between 'm_map' and 't_map'?

**Comment by WDdeBWT** [comment]
Convert timestamp to natural number, t_ Map is responsible for selecting the year, M_ Map is responsible for distinguishing the first and second half of the year.
I am not the author, the above is my personal understanding

**Comment by wangjlgz** [comment]
Thanks @WDdeBWT for answering the question.
